version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_ROOT_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILE: "DEV"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ./db/postgres:/data/db
    stdin_open: true
    tty: true

volumes:
  db: